### we are only working with summer olympics

In [2]:
import pandas as pd
import numpy as np

In [3]:
path_athelete = "../data/athlete_events.csv"
path_region = "../data/noc_regions.csv"

df = pd.read_csv(path_athelete)
region_df = pd.read_csv(path_region)

In [4]:
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='str')

In [5]:
region_df.columns

Index(['NOC', 'region', 'notes'], dtype='str')

In [6]:
df.shape

(271116, 15)

In [7]:
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='str')

In [8]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [9]:
### Filter data on the basis of Summer 

df = df[df['Season'] == 'Summer'] 
df.head(6)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
27,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,NaN

In [10]:
region_df.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [11]:
''' 
Merge df and region_df because NOC is common in both table and we get a 
table having countries name also !!
'''
df = df.merge(region_df , on='NOC' , how='left')
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN

In [12]:
df['region'].unique()  # shows total number of unique teams participate in olympics

<StringArray>
[           'China',          'Denmark',      'Netherlands',
          'Finland',           'Norway',          'Romania',
          'Estonia',           'France',          'Morocco',
            'Spain',
 ...
            'Aruba',            'Nauru',          'Vietnam',
           'Bhutan', 'Marshall Islands',         'Kiribati',
            'Tonga',           'Kosovo',      'South Sudan',
          'Lesotho']
Length: 206, dtype: str

In [13]:
df['region'].unique().shape  # provide number of unique values

(206,)

In [14]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9189
Height     51857
Weight     53854
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     188464
region       370
notes     218151
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(1385)

In [16]:
df.drop_duplicates( inplace=True )

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN

In [19]:
medal_count = df['Medal'].value_counts()
print( medal_count )
print( type(medal_count) )

Medal
Gold      11456
Bronze    11409
Silver    11212
Name: count, dtype: int64
<class 'pandas.Series'>

In [20]:
# get_dummies -> function used to find

pd.get_dummies(df['Medal'])

        Bronze   Gold  Silver
0        False  False   False
1        False  False   False
2        False  False   False
3        False   True   False
4        False  False   False
...        ...    ...     ...
222547   False  False   False
222548   False  False   False
222549   False  False   False
222550   False  False   False
222551   False  False   False

[221167 rows x 3 columns]

In [21]:
df = pd.concat([df,pd.get_dummies(df['Medal'])],axis=1)
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,False,False,False
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,False,False,False
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,False,False,False
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,False,True,False
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,False,False,False

In [22]:
# df = df.loc[:, ~df.columns.duplicated()]

In [23]:
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal', 'region', 'notes',
       'Bronze', 'Gold', 'Silver'],
      dtype='str')

In [24]:
df.groupby('NOC')[['Gold','Silver','Bronze']].sum() \
  .sort_values(by='Gold', ascending=False) \
  .reset_index()

# In this data set there is mistake count medal multiple times as they held in a 
# same year of same sport like a hockey team win a gold in a specific year so count as 1 but it count as = Number of players*Gold

     NOC  Gold  Silver  Bronze
0    USA  2472    1333    1197
1    URS   832     635     596
2    GBR   635     729     620
3    GER   592     538     649
4    ITA   518     474     454
..   ...   ...     ...     ...
225  WIF     0       0       5
226  YEM     0       0       0
227  YAR     0       0       0
228  YMD     0       0       0
229  ZAM     0       1       1

[230 rows x 4 columns]

In [25]:
# This is the problem for india win a GOLD medal in hockey and it count 14 because hockey has 14 total num of player
df[ (df['NOC'] == 'IND')  &  (df['Medal'] == 'Gold' ) & ( df['Sport'] == 'Hockey') & ( df['Year'] == 1928 )].head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
4186,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False
4460,2864,Richard James Allen,M,25.0,172.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False
32103,19716,Dhyan Chand Bais,M,22.0,169.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False
64140,39020,Michael Anthony Gateley,M,23.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False
68522,41710,"William James ""Willie"" Goodsir-Cullen",M,21.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False

In [65]:
# Fix: Count team medals as 1 medal per event, not per player
# Drop duplicates based on the EVENT won (NOC + Year + Sport + Event + Medal)
# This ensures: Team sports (Hockey, Basketball) = 1 medal, Individual sports = 1 medal per athlete
df = df.drop_duplicates(subset=['NOC','Games','Year','Season','City','Sport','Event','Medal','region','notes','Bronze','Gold','Silver'])
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,False,False,False
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,False,False,False
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,False,False,False
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,False,True,False
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,False,False,False

In [27]:
# Verify: India's gold medals should now be much lower (team sports counted as 1)
# Before fix: 131 (counted each hockey player individually)
# After fix: Should count each unique event only once
df[ (df['NOC'] == 'IND')  &  (df['Medal'] == 'Gold' )].shape

(9, 20)

In [28]:
# Verify hockey example: India 1928 Gold should now be 1 medal, not 14 (one per player)
print('India 1928 Hockey Gold - rows after fix:')
print(df[ (df['NOC'] == 'IND') & (df['Medal'] == 'Gold') & (df['Sport'] == 'Hockey') & (df['Year'] == 1928) ].shape)
print('\nBefore fix this was 14 rows (one per player), now it should be 1 row (one team medal)')
df[ (df['NOC'] == 'IND') & (df['Medal'] == 'Gold') & (df['Sport'] == 'Hockey') & (df['Year'] == 1928) ].head()

India 1928 Hockey Gold - rows after fix:
(1, 20)

Before fix this was 14 rows (one per player), now it should be 1 row (one team medal)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
4186,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False

In [29]:
# Now this medal tally has correct data about the medal with specific nation.
# Team sports (like Hockey, Basketball) now count as 1 medal per event, not per player.
df.shape

(105168, 20)

In [38]:
medal_tally = df.groupby('Year')[['Gold','Silver','Bronze']].sum() \
  .sort_values(by='Gold', ascending=False) \
  .reset_index()

In [31]:
medal_tally['total'] = medal_tally['Gold'] + medal_tally['Silver'] + medal_tally['Bronze']

medal_tally =

    Year  Gold  Silver  Bronze  total
0   2016   307     306     360    973
1   2008   302     302     353    957
2   2012   302     304     356    962
3   2004   301     300     326    927
4   2000   299     300     326    925
5   1996   271     273     297    841
6   1992   260     257     296    813
7   1988   240     234     264    738
8   1984   224     218     243    685
9   1980   204     204     223    631
10  1976   198     199     216    613
11  1972   195     195     210    600
12  1968   174     170     183    527
13  1964   163     166     172    501
14  1920   155     152     139    446
15  1956   153     153     161    467
16  1960   152     149     160    461
17  1952   149     151     157    457
18  1948   144     146     149    439
19  1936   141     140     141    422
20  1924   129     131     131    391
21  1932   125     125     120    370
22  1928   119     118     119    356
23  1908   109     106     105    320
24  1912   108     104     104    316
25  1900   101      98      92    291
26  1904    97      93      89    279
27  1906    74      77      73    224
28  1896    44      41      35    120

In [ ]:
years = df['Year'].unique().tolist()
years.sort()
years.insert(0,'overall')

years

In [ ]:
regions = np.unique( df['region'].dropna().values).tolist()
regions.sort()
regions.insert(0,'overall')
regions

In [41]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,False,False,False
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,False,False,False
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,False,False,False
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,False,True,False
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,False,False,False

In [53]:
unique_country = df['region'].unique()
lst = unique_country.to_numpy()
type( lst )

lst.shape[0]

206

In [54]:
edition = df['Year'].unique()
edition.shape[0] -1

28

In [57]:
unique_cities = df['City'].unique()
unique_cities.shape[0]

23

In [60]:
unique_games = df['Sport'].unique()
unique_games.shape[0]

52

In [62]:
unique_athelete = df['Name'].unique().shape[0]
unique_athelete

63163

In [ ]:
Cunique_events

651