### we are only working with summer olympics

In [3]:
import pandas as pd
import numpy as np

In [4]:
path_athelete = "../data/athlete_events.csv"
path_region = "../data/noc_regions.csv"

df = pd.read_csv(path_athelete)
region_df = pd.read_csv(path_region)

In [5]:
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')

In [6]:
region_df.columns

Index(['NOC', 'region', 'notes'], dtype='object')

In [7]:
df.shape

(271116, 15)

In [8]:
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')

In [9]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [10]:
### Filter data on the basis of Summer 

df = df[df['Season'] == 'Summer'] 
df.head(6)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
27,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 4 x 100 metres Relay,NaN

In [11]:
region_df.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [12]:
''' 
Merge df and region_df because NOC is common in both table and we get a 
table having countries name also !!
'''
df = df.merge(region_df , on='NOC' , how='left')
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN

In [13]:
df['region'].unique().shape

(206,)

In [14]:
df['region'].unique()  # shows total number of unique teams participate in olympics

array(['China', 'Denmark', 'Netherlands', 'Finland', 'Norway', 'Romania',
       'Estonia', 'France', 'Morocco', 'Spain', 'Egypt', 'Iran',
       'Bulgaria', 'Italy', 'Chad', 'Azerbaijan', 'Sudan', 'Russia',
       'Argentina', 'Cuba', 'Belarus', 'Greece', 'Cameroon', 'Turkey',
       'Chile', 'Mexico', 'USA', 'Nicaragua', 'Hungary', 'Nigeria',
       'Algeria', 'Kuwait', 'Bahrain', 'Pakistan', 'Iraq', 'Syria',
       'Lebanon', 'Qatar', 'Malaysia', 'Germany', 'Canada', 'Ireland',
       'Australia', 'South Africa', 'Eritrea', 'Tanzania', 'Jordan',
       'Tunisia', 'Libya', 'Belgium', 'Djibouti', 'Palestine', 'Comoros',
       'Kazakhstan', 'Brunei', 'India', 'Saudi Arabia', 'Maldives',
       'Ethiopia', 'United Arab Emirates', 'Yemen', 'Indonesia',
       'Philippines', nan, 'Uzbekistan', 'Kyrgyzstan', 'Tajikistan',
       'Japan', 'Republic of Congo', 'Switzerland', 'Brazil', 'Monaco',
       'Israel', 'Uruguay', 'Sweden', 'Sri Lanka', 'Armenia',
       'Ivory Coast', 'Kenya', 'Benin', 'UK', 'Ghana', 'Somalia', 'Niger',
       'Mali', 'Afghanistan', 'Poland', 'Costa Rica', 'Panama', 'Georgia',
       'Slovenia', 'Guyana', 'New Zealand', 'Portugal', 'Paraguay',
       'Angola', 'Venezuela', 'Colombia', 'Bangladesh', 'Peru',
       'El Salvador', 'Puerto Rico', 'Uganda', 'Honduras', 'Ecuador',
       'Turkmenistan', 'Mauritius', 'Seychelles', 'Czech Republic',
       'Luxembourg', 'Mauritania', 'Saint Kitts', 'Trinidad',
       'Dominican Republic', 'Saint Vincent', 'Jamaica', 'Liberia',
       'Suriname', 'Nepal', 'Mongolia', 'Austria', 'Palau', 'Lithuania',
       'Togo', 'Namibia', 'Curacao', 'Ukraine', 'Iceland',
       'American Samoa', 'Samoa', 'Rwanda', 'Croatia', 'Dominica',
       'Haiti', 'Malta', 'Cyprus', 'Guinea', 'Belize', 'Thailand',
       'Bermuda', 'Serbia', 'Sierra Leone', 'Papua New Guinea',
       'Individual Olympic Athletes', 'Oman', 'Fiji', 'Vanuatu',
       'Moldova', 'Bahamas', 'Guatemala', 'Latvia',
       'Virgin Islands, British', 'Mozambique', 'Virgin Islands, US',
       'Central African Republic', 'Madagascar', 'Bosnia and Herzegovina',
       'Guam', 'Cayman Islands', 'Slovakia', 'Barbados', 'Guinea-Bissau',
       'Timor-Leste', 'Democratic Republic of the Congo', 'Gabon',
       'San Marino', 'Laos', 'Botswana', 'South Korea', 'Cambodia',
       'North Korea', 'Solomon Islands', 'Senegal', 'Cape Verde',
       'Equatorial Guinea', 'Boliva', 'Antigua', 'Andorra', 'Zimbabwe',
       'Grenada', 'Saint Lucia', 'Micronesia', 'Myanmar', 'Malawi',
       'Zambia', 'Taiwan', 'Sao Tome and Principe', 'Macedonia',
       'Liechtenstein', 'Montenegro', 'Gambia', 'Cook Islands', 'Albania',
       'Swaziland', 'Burkina Faso', 'Burundi', 'Aruba', 'Nauru',
       'Vietnam', 'Bhutan', 'Marshall Islands', 'Kiribati', 'Tonga',
       'Kosovo', 'South Sudan', 'Lesotho'], dtype=object)

In [15]:
df['region'].unique().shape  # provide number of unique values

(206,)

In [16]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9189
Height     51857
Weight     53854
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     188464
region       370
notes     218151
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(1385)

In [18]:
df.drop_duplicates( inplace=True )

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN

In [21]:
medal_count = df['Medal'].value_counts()
print( medal_count )
print( type(medal_count) )

Medal
Gold      11456
Bronze    11409
Silver    11212
Name: count, dtype: int64
<class 'pandas.core.series.Series'>

In [22]:
# get_dummies -> function used to find

pd.get_dummies(df['Medal'])

        Bronze   Gold  Silver
0        False  False   False
1        False  False   False
2        False  False   False
3        False   True   False
4        False  False   False
...        ...    ...     ...
222547   False  False   False
222548   False  False   False
222549   False  False   False
222550   False  False   False
222551   False  False   False

[221167 rows x 3 columns]

In [23]:
df = pd.concat([df,pd.get_dummies(df['Medal'])],axis=1)
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,False,False,False
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,False,False,False
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,False,False,False
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,False,True,False
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,False,False,False

In [24]:
# df = df.loc[:, ~df.columns.duplicated()]

In [25]:
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal', 'region', 'notes',
       'Bronze', 'Gold', 'Silver'],
      dtype='object')

In [26]:
df.groupby('NOC')[['Gold','Silver','Bronze']].sum() \
  .sort_values(by='Gold', ascending=False) \
  .reset_index()

# In this data set there is mistake count medal multiple times as they held in a 
# same year of same sport like a hockey team win a gold in a specific year so count as 1 but it count as = Number of players*Gold

     NOC  Gold  Silver  Bronze
0    USA  2472    1333    1197
1    URS   832     635     596
2    GBR   635     729     620
3    GER   592     538     649
4    ITA   518     474     454
..   ...   ...     ...     ...
225  WIF     0       0       5
226  YEM     0       0       0
227  YAR     0       0       0
228  YMD     0       0       0
229  ZAM     0       1       1

[230 rows x 4 columns]

In [27]:
# This is the problem for india win a GOLD medal in hockey and it count 14 because hockey has 14 total num of player
df[ (df['NOC'] == 'IND')  &  (df['Medal'] == 'Gold' ) & ( df['Sport'] == 'Hockey') & ( df['Year'] == 1928 )].head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
4186,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False
4460,2864,Richard James Allen,M,25.0,172.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False
32103,19716,Dhyan Chand Bais,M,22.0,169.0,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False
64140,39020,Michael Anthony Gateley,M,23.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False
68522,41710,"William James ""Willie"" Goodsir-Cullen",M,21.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False

In [28]:
df.duplicated(subset=['NOC','Games','Year','Season','City','Sport','Event','Medal','region','notes','Bronze','Gold','Silver'])

0         False
1         False
2         False
3         False
4         False
          ...
222547     True
222548     True
222549     True
222550     True
222551     True
Length: 221167, dtype: bool

In [29]:
# Fix: Count team medals as 1 medal per event, not per player
# Drop duplicates based on the EVENT won (NOC + Year + Sport + Event + Medal)
# This ensures: Team sports (Hockey, Basketball) = 1 medal, Individual sports = 1 medal per athlete
df = df.drop_duplicates(subset=['NOC','Games','Year','Season','City','Sport','Event','Medal','region','notes','Bronze','Gold','Silver'])
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,False,False,False
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,False,False,False
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,False,False,False
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,False,True,False
4,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,False,False,False

In [30]:
df.duplicated().shape

(105168,)

In [31]:
# Verify: India's gold medals should now be much lower (team sports counted as 1)
# Before fix: 131 (counted each hockey player individually)
# After fix: Should count each unique event only once
df[ (df['NOC'] == 'IND')  &  (df['Medal'] == 'Gold' )].shape

(9, 20)

In [32]:
# Verify hockey example: India 1928 Gold should now be 1 medal, not 14 (one per player)
print('India 1928 Hockey Gold - rows after fix:')
print(df[ (df['NOC'] == 'IND') & (df['Medal'] == 'Gold') & (df['Sport'] == 'Hockey') & (df['Year'] == 1928) ].shape)
print('\nBefore fix this was 14 rows (one per player), now it should be 1 row (one team medal)')
df[ (df['NOC'] == 'IND') & (df['Medal'] == 'Gold') & (df['Sport'] == 'Hockey') & (df['Year'] == 1928) ].head()

India 1928 Hockey Gold - rows after fix:
(1, 20)

Before fix this was 14 rows (one per player), now it should be 1 row (one team medal)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
4186,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,Gold,India,NaN,False,True,False

In [33]:
# Now this medal tally has correct data about the medal with specific nation.
# Team sports (like Hockey, Basketball) now count as 1 medal per event, not per player.
df.shape

(105168, 20)

In [34]:
medal_tally = df.groupby('Year')[['Gold','Silver','Bronze']].sum() \
  .sort_values(by='Gold', ascending=False) \
  .reset_index()

In [35]:
medal_tally['total'] = medal_tally['Gold'] + medal_tally['Silver'] + medal_tally['Bronze']

medal_tally =

SyntaxError: invalid syntax (3830734425.py, line 3)

In [ ]:
years = df['Year'].unique().tolist()
years.sort()
years.insert(0,'overall')

years

In [ ]:
regions = np.unique( df['region'].dropna().values).tolist()
regions.sort()
regions.insert(0,'overall')
regions

In [ ]:
df.head()

In [ ]:
unique_country = df['region'].unique()
lst = unique_country.to_numpy()
type( lst )

lst.shape[0]

In [ ]:
edition = df['Year'].unique()
edition.shape[0] -1

In [ ]:
unique_cities = df['City'].unique()
unique_cities.shape[0]

In [ ]:
unique_games = df['Sport'].unique()
unique_games.shape[0]

In [ ]:
unique_athelete = df['Name'].unique().shape[0]
unique_athelete

In [ ]:
unique_country_arr = df['Year'].unique()
type( unique_country_arr)
lst = unique_country_arr.tolist()

In [ ]:
df[ (df['Year'] == 1992) &  (df['Sport'] == 'Basketball') & ( df['NOC'] == 'CHN' )]

In [ ]:
new_df = df.drop_duplicates( ['Year' , 'region' ])
year_region = new_df.groupby(['Year'])['region'].size().reset_index()
year_region.shape

type( year_region['region'].to_list() )

year_region['region'].to_list()

In [ ]:
!pip install plotly
!pip install nbformat

Requirement already satisfied: plotly in C:\Users\sarth\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\sarth\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from plotly) (2.18.0)
Requirement already satisfied: packaging in C:\Users\sarth\AppData\Roaming\Python\Python314\site-packages (from plotly) (26.0)
Collecting nbformat
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting fastjsonschema>=2.15 (from nbformat)
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\sarth\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\sarth\AppData\Roaming\Python\Python314\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\sarth\AppData\Roaming\Python\Python314\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\sarth\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\sarth\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\sarth\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\sarth\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\sarth\AppData\Roaming\Python\Python314\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.2)
Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Using cached fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Installing collected packages: fastjsonschema, nbformat

   -------------------- ------------------- 1/2 [nbformat]
   ---------------------------------------- 2/2 [nbformat]

Successfully installed fastjsonschema-2.21.2 nbformat-5.10.4

  WARNING: The script jupyter-trust.exe is installed in 'C:\Users\sarth\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [36]:
import plotly.express as px

# Step 1: Remove duplicates
new_df = df.drop_duplicates(['Year', 'region'])

# Step 2: Count countries per year
year_region = new_df.groupby('Year')['region'].size().reset_index()

# Rename column for clarity
year_region.rename(columns={'region': 'num_countries'}, inplace=True)

# Step 3: Plot using Plotly
fig = px.line(
    year_region,
    x='Year',
    y='num_countries',
    title='Number of Countries Participating in Olympics Over Years'
)

# import plotly.io as pio
# pio.renderers.default = 'browser'

fig.show()