In [1]:
import pandas as pd 
import numpy as np

In [2]:
path_athelete = "../data/athlete_events.csv"
path_region = "../data/noc_regions.csv"

df = pd.read_csv(path_athelete)
region_df = pd.read_csv(path_region)

In [3]:
print( df.columns )
print( region_df.columns)

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')
Index(['NOC', 'region', 'notes'], dtype='object')

In [4]:
df = df.merge( region_df , on = 'NOC' , how='inner' )
df = df[df['Season'] == 'Summer']
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN

In [5]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9177
Height     51769
Weight     53764
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     188124
region        21
notes     217802
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(1385)

In [7]:
df.drop_duplicates( inplace= True )
df.duplicated().sum()

np.int64(0)

In [8]:
df = pd.concat([df , pd.get_dummies(df['Medal']) ] , axis=1)
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,Bronze,Gold,Silver
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,False,False,False
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,False,False,False
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,False,False,False
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,False,True,False
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN,Netherlands,NaN,False,False,False

In [57]:
# new_df = df.dropna(subset=['Medal'])
# new_df = new_df.groupby(['Name','Sport'])[['Gold','Silver','Bronze']].sum()
# new_df['Total'] = new_df['Gold'] + new_df['Silver'] + new_df['Bronze']
# new_df = new_df.sort_values( by='Total' , ascending=False)
# new_df.head(15)

,,Gold,Silver,Bronze,Total
Name,Sport,,,,
"Michael Fred Phelps, II",Swimming,23,3,2,28
Larysa Semenivna Latynina (Diriy-),Gymnastics,9,5,4,18
Nikolay Yefimovich Andrianov,Gymnastics,7,5,3,15
Edoardo Mangiarotti,Fencing,6,5,2,13
Borys Anfiyanovych Shakhlin,Gymnastics,7,4,2,13
Takashi Ono,Gymnastics,5,4,4,13
Ryan Steven Lochte,Swimming,6,3,3,12
Natalie Anne Coughlin (-Hall),Swimming,3,4,5,12
Sawao Kato,Gymnastics,8,3,1,12
Paavo Johannes Nurmi,Athletics,9,3,0,12
"Jennifer Elisabeth ""Jenny"" Thompson (-Cumpelik)",Swimming,8,3,1,12
"Dara Grace Torres (-Hoffman, -Minas)",Swimming,4,4,4,12
Aleksey Yuryevich Nemov,Gymnastics,4,2,6,12
Birgit Fischer-Schmidt,Canoeing,8,4,0,12
Mark Andrew Spitz,Swimming,9,1,1,11

In [56]:


# sport_table = df.dropna(subset='Medal')
# sport_table = df[['Name' , 'Sport']]
# sport_table = sport_table.drop_duplicates( subset=['Name','Sport'])
# sport_table

                                      Name       Sport
0                                A Dijiang  Basketball
1                                 A Lamusi        Judo
2                      Gunnar Nielsen Aaby    Football
3                     Edgar Lindenau Aabye  Tug-Of-War
26      Cornelia "Cor" Aalten (-Strannood)   Athletics
...                                    ...         ...
270753           Olesya Nikolayevna Zykina   Athletics
270756            Fernando scar Zylberberg      Hockey
270758          James Francis "Jim" Zylker    Football
270759        Aleksandr Viktorovich Zyuzin      Rowing
270761              Olga Igorevna Zyuzkova  Basketball

[117105 rows x 2 columns]

In [58]:
# new = new_df.merge( sport_table , on = 'Name' , how='inner')
# new.head(15)

,Name,Gold,Silver,Bronze,Total,Sport
0,"Michael Fred Phelps, II",23,3,2,28,Swimming
1,Larysa Semenivna Latynina (Diriy-),9,5,4,18,Gymnastics
2,Nikolay Yefimovich Andrianov,7,5,3,15,Gymnastics
3,Edoardo Mangiarotti,6,5,2,13,Fencing
4,Borys Anfiyanovych Shakhlin,7,4,2,13,Gymnastics
5,Takashi Ono,5,4,4,13,Gymnastics
6,Takashi Ono,5,4,4,13,Judo
7,Ryan Steven Lochte,6,3,3,12,Swimming
8,Natalie Anne Coughlin (-Hall),3,4,5,12,Swimming
9,Sawao Kato,8,3,1,12,Gymnastics
10,Paavo Johannes Nurmi,9,3,0,12,Athletics
11,"Jennifer Elisabeth ""Jenny"" Thompson (-Cumpelik)",8,3,1,12,Swimming
12,"Dara Grace Torres (-Hoffman, -Minas)",4,4,4,12,Swimming
13,Aleksey Yuryevich Nemov,4,2,6,12,Gymnastics
14,Birgit Fischer-Schmidt,8,4,0,12,Canoeing

In [ ]:
# Step 1: Keep only medal winners
df_medal = df[df['Medal'].notnull()]

# Step 2: Group by Name + Sport + Region
medal_sport_df = df_medal.groupby(
    ['Name', 'Sport', 'region']
)[['Gold', 'Silver', 'Bronze']].sum().reset_index()

# Step 3: Add total medals
medal_sport_df['Total'] = (
    medal_sport_df['Gold'] +
    medal_sport_df['Silver'] +
    medal_sport_df['Bronze']
)

# Step 4: Sort
medal_sport_df = medal_sport_df.sort_values(by='Total', ascending=False)

table = medal_sport_df[['Name','Sport','region','Gold' ,'Silver','Bronze','Total']]
table.reset_index().drop('index',axis=1)



# Step 5: Optional → top 10
# top_players = medal_sport_df

# top_players.head(15)


# top_players[top_players['Sport'] == 'Gymnastics'].head(15)

,Name,Sport,region,Gold,Silver,Bronze,Total
0,"Michael Fred Phelps, II",Swimming,USA,23,3,2,28
1,Larysa Semenivna Latynina (Diriy-),Gymnastics,Russia,9,5,4,18
2,Nikolay Yefimovich Andrianov,Gymnastics,Russia,7,5,3,15
3,Borys Anfiyanovych Shakhlin,Gymnastics,Russia,7,4,2,13
4,Takashi Ono,Gymnastics,Japan,5,4,4,13
...,...,...,...,...,...,...,...
24704,Aage Marius Hansen,Gymnastics,Denmark,0,0,1,1
24705,Aage Jrgensen,Gymnastics,Denmark,0,1,0,1
24706,Aage Jrgen Christian Andersen,Football,Denmark,1,0,0,1
24707,Aage Ingvar Eriksen,Wrestling,Norway,0,1,0,1
24708,Aage Hy Pedersen,Sailing,Denmark,0,1,0,1